spring:
  application:
    name: demo
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    ollama:
      chat:
        model: llama3.2
      embedding:
        model: all-minilm # Ref: https://github.com/spring-projects/spring-ai/issues/840
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  docker:
    compose:
      lifecycle-management: start_only
      file: docker/compose.yml
  threads:
    virtual:
      enabled: true
