spring:
  application:
    name: joshlong-spring-demo-kotlin
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    ollama:
      chat:
        model: all-minilm # Ref: https://github.com/spring-projects/spring-ai/issues/840
      embedding:
        model: all-minilm
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      lifecycle-management: start_and_stop
      file: docker/compose.yml
